### ISSUE TITLE
Getting Kamikaze2 working on a BBB Wireless

### ISSUE THREAD

**Issue by gruvin** [eliasbakken/Kamikaze2#8]
My first BBB just happens to be the Wireless version, which has no Ethernet port. This results in the Kamikaze2 image failing to boot. Here's how I (mostly) got around it ...

_[copied from my original  [goeland86/Kamikaze2 issue #20](https://github.com/goeland86/Kamikaze2/issues/20) post. I didn't notice that repo was a fork and figured people may find this here, first.]_

The first and main issue was not being able to boot the **Kamikaze2 image** on the BBB **Wireless**. The complaint was a missing `boneblack-wireless.dtb` (name from memory) file. [Indeed, there isn't one and going to pains to provide one didn't help.] I fixed that by editing `uEnv.txt` and uncommenting the following line ...

```
dtb=am335x-boneblack-overlay.dtb
```

Now the kernel boots up. But because there's no `eth0` phy, the start-up scripts block. The fix for that was to comment out the following two lines in `/etc/network/interfaces` ...
 
```
#auto eth0
#iface eth0 inet dhcp
```

I found an old Apple USB-to-Ethernet adapter in my junk drawer and used that to get Internet connectivity. Using `dmesg`, I found that it had some funky device name, resulting in the addition of the following, again in `/etc/network/interfaces`) ...

```
auto enxb88d1254404f
iface enxb88d1254404f inet dhcp
```

---

There's now a really weird, funky thing going on with the serial console, making it completely unusable. I don't have a working fix for that.

--- 

So now, finally, visiting `http://kamikaze.local` (which takes a long time to load, the first time) eventually results in OctoPrint's start-up page. 

Looking in `/dev/` I see ...

```
root@kamikaze:~# ls -1 /dev/octoprint_*
/dev/octoprint_0
/dev/octoprint_1
```

Not sure why there are two. But OctoPrint only shows the `_1`. So whatever.

There is no `wlan0` interface, despite using the `am335x-boneblack-overlay.dtb` file, which suggests to me that is _should_ be present. So, still no WiFi. :'( 

At least I can play with Redeem now, to get to know how it works and so on.

In hindsight, a standard BBB Ethernet board, with an external USB WiFi dongle, would have been a better idea! Live and learn.

Hope that helps.

**Comment by gruvin** [comment]
Referring to the above, having now hooked up a bunch of steppers, hot end, fans, limit switches, etc ...

Steppers and fans appear to all be working properly. But heater outputs (both hot end and bed) are not responding at all. Zero Volts on outputs. 

_(There's also something weird going on with the Z end stop, on the Redeem end of things -- it triggers according to terminal output, but homing doesn't seem to notice. But I think that's for another topic/time/place.)_ 

In any case, I'm guessing that the .dtb file I've fudged in as mentioned above isn't correctly configuring the kernel for the Replicape on a BBB **Wireless** -- if that's even how that works???

If my guess is right, then how might I go about testing for or replacing the `.dtb` with one that might work? I see there's another repo here for compiling `dts` to `dtb` files, etc. But I have no idea where to start, as regards the Replicape, specifically. A pointer to the current set-up for the original BBB (Ethernet) might be enough for me to figure out what is needed.

WiFi is a whole other problem. Apparently the current packaged kernels simply don't have the drivers. So never mind that, for now. 

Of course, if I'm guessing up the wrong tree, as it were, I'd love to know that, too! :-)

Thanks!

**Comment by goeland86** [comment]
Just a quick sanity check, are your thermistors reporting temps? Do you see a temp change alarm in redeem log / octoprint terminal?

**Comment by gruvin** [comment]
@goeland86 Yup. Thermistors reporting temps OK. 

EDIT: Oh! It's working today! Hmmm. Not sure what that's about. Haven't changed anything and I did at least a couple power-down / restarts yesterday. Oh ... the USB cable got unplugged at some point, when I realised it was back-feeding 5V into stepper drivers or something. Maybe that's it? Never mind then. Onwards and upwards.

```
Send: M105
Recv: ok T:20.7/0.0 T1:0.0/0.0 T0:20.7/0.0 B:19.7/0.0 @:0.0
Send: M104 S180.000000
Recv: ok
...
...
Recv: ok T:181.2/180.0 T1:0.0/0.0 T0:181.2/180.0 B:20.0/0.0 @:45.0
...
...
Send: M104 S0.000000
Recv: ok
```

**Comment by gruvin** [comment]
Looks like everything is working for me now, minus WiFi support, due to kernel drivers not yet present. That's fine. All in good time, I'm sure.

I'll close this issue to cut down on confusion / noise, letting @eliasbakken concentrate on the manga thing. Let's continue (if needed) over at [@goeland86 Issue #20](https://github.com/goeland86/Kamikaze2/issues/20).

Keep up the great work guys!
